#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

rm -f constant/polyMesh/boundary > /dev/null 2>&1
rm -rf fluentInterface
rm -r 1* 2* 3* 4* 5* 6* 7* 8* 9*

#------------------------------------------------------------------------------
