#!/bin/sh



#local
#cd /home/thailsson/Projetos/server/api-openfoam/cases/elbow/
#foamToVTK -allPatches
#mkdir /home/thailsson/Projetos/server/test/$1
#cp VTK/elbow_* /home/thailsson/Projetos/server/test/$1/.

#server
cd /home/clementino1971_2013/api-openfoam/cases/elbow/
foamToVTK -allPatches -useTimeName
mkdir /home/clementino1971_2013/test/$1
cp VTK/elbow_* /home/clementino1971_2013/test/$1/.
