#!/bin/sh

#local
#cd /home/thailsson/Projetos/server/api-openfoam/cases/cavity/
#foamToVTK -allPatches
#mkdir /home/thailsson/Projetos/server/test/$1
#cp VTK/cavity_* /home/thailsson/Projetos/server/test/$1/.

#server
cd /home/clementino1971_2013/api-openfoam/cases/cavity/
foamToVTK -allPatches -useTimeName
mkdir /home/clementino1971_2013/test/$1
cp VTK/cavity_* /home/clementino1971_2013/test/$1/.
